#!/bin/sh

# When copying the contents of this file, remember to name the new file using only valid characters [a-zA-Z0-9_-]
# Fullstops '.' and file extensions are not permitted

set -eux

# Change user to ubuntu to prevent running container as root
su ubuntu

cd /etc/chatops/cloud-docker-images/cloud-chatops
git fetch && git clean -fxd && git reset --hard origin/master

docker compose up -d

echo "complete"