#!/bin/sh

# When copying the contents of this file, remember to name the new file using only valid characters [a-zA-Z0-9_-]
# Fullstops '.' and file extensions are not permitted

set -eux

# If run as root change user to ubuntu to prevent running container with root privileges
if [ "$(id -u)" -eq 0 ]; then
    exec sudo -H -u ubuntu $0 "$@"
fi

cd /etc/chatops/cloud-docker-images/cloud-chatops
git fetch && git clean -fxd && git reset --hard origin/master

docker compose up -d

echo "complete"