---
app:  # Configuration for the app
  users:
    - realName: Real Name
      slackID: slack_id
      githubName: github_username
      gitlabName: gitlab_username


github:  # Configuration for the GitHub feature
  enabled: true  # Disable if you do not want GitHub pull request reminders
  repositories:
    <owner>:
      - <repo>

gitlab:  # Configuration for the GitLab feature
  enabled: true  # Disable if you do not want GitHub pull request reminders
  domain: gitlab.example.com
  projects:
    <group>:
      - <project>
